name: diary_flutter
description: "A Flutter implementation for Diary."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  mongol: ^7.0.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  custom_lint: ^0.6.2
  test: ^1.24.9

dependency_overrides:
  analyzer: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Longzhao
      fonts:
        - asset: fonts/fz_longzhao_fw.ttf
    - family: KhangxiDictTrial
      fonts:
        - asset: fonts/tpld_khangxidicttrial.otf
